/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.western;


import javax.swing.*;
import java.awt.*;

import java.awt.Color;
import org.kordamp.ikonli.remixicon.RemixiconAL;
import org.kordamp.ikonli.remixicon.RemixiconMZ;
import org.kordamp.ikonli.swing.FontIcon;

import java.util.LinkedList;

/**
 *
 * @author Liam
 */
public class POIListPopup extends javax.swing.JPanel {

    private Room room;
    private LinkedList<POI> POIs;
    
    /**
     * Creates new form POIListPopup
     */
    public POIListPopup(Room room, LinkedList<POI> POIs) {
        
        this.room = room;
        this.POIs = POIs;
        initComponents();
        //ButtonContainer.setSize(ButtonContainer.getParent().getSize());
        
        setLabel();
        initButtons();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ExitButton = new javax.swing.JButton();
        ScrollPane = new javax.swing.JScrollPane();
        ButtonContainer = new javax.swing.JPanel();
        ChangeNameButton = new javax.swing.JButton();
        DeleteButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setMinimumSize(new java.awt.Dimension(402, 180));

        jLabel1.setText("ROOM# POIs:");
        jLabel1.setMaximumSize(new java.awt.Dimension(352, 16));
        jLabel1.setMinimumSize(new java.awt.Dimension(170, 16));

        ExitButton.setBorder(null);
        ExitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitButtonMouseClicked(evt);
            }
        });
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });

        ScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        ButtonContainer.setMinimumSize(new java.awt.Dimension(386, 60));
        ButtonContainer.setPreferredSize(new java.awt.Dimension(386, 60));
        ButtonContainer.setLayout(new java.awt.GridLayout(0, 1));
        ScrollPane.setViewportView(ButtonContainer);

        ChangeNameButton.setBackground(new java.awt.Color(51, 51, 255));
        ChangeNameButton.setForeground(new java.awt.Color(255, 255, 255));
        ChangeNameButton.setText("Change Name");
        ChangeNameButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ChangeNameButtonMouseClicked(evt);
            }
        });
        ChangeNameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangeNameButtonActionPerformed(evt);
            }
        });

        DeleteButton.setBackground(new java.awt.Color(255, 51, 51));
        DeleteButton.setForeground(new java.awt.Color(255, 255, 255));
        DeleteButton.setText("Delete");
        DeleteButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteButtonMouseClicked(evt);
            }
        });
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ScrollPane)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(194, 194, 194)
                        .addComponent(ExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(ChangeNameButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(DeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ExitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ChangeNameButton)
                    .addComponent(DeleteButton))
                .addContainerGap(8, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void ExitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitButtonMouseClicked
        
        close();
               
    }//GEN-LAST:event_ExitButtonMouseClicked

    private void ChangeNameButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChangeNameButtonMouseClicked
        String name = JOptionPane.showInputDialog(this, "New room name:");
        if (name == null) return;
        room.setRoomNumber(name);
        setLabel();
        
    }//GEN-LAST:event_ChangeNameButtonMouseClicked

    private void ChangeNameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangeNameButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChangeNameButtonActionPerformed

    private void DeleteButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteButtonMouseClicked
        room.delete();
        close();
    }//GEN-LAST:event_DeleteButtonMouseClicked

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void setLabel() {
        jLabel1.setText(room.getBuilding().getShortName() + " " + room.getRoomNumber()+" POIs:");
    }
    
    //closes the popup
    public void close() {
        
        Container parent = this.getParent();
        parent.remove(this);
        parent.revalidate();
        parent.repaint();
        room.deletePopup();
        
    }
    
    private void initButtons() {
        
        //set exit button icons
        ExitButton.setIcon(FontIcon.of(RemixiconAL.CLOSE_FILL, 24));
        ExitButton.setPressedIcon(FontIcon.of(RemixiconAL.CLOSE_FILL, 24, Color.RED));
        //
        
        //create buttons for POIs in list
        for (POI poi:POIs) {
                       
            JButton button = new POIButton(poi, this);
            ButtonContainer.add(button);
            button.setSize(ScrollPane.getPreferredSize().width, POIButton.HEIGHT);
            
        }
        //
        
        if (!MainWindow.curUser.isAdmin())
        {
            
            DeleteButton.setVisible(false);
            DeleteButton.setEnabled(false);
            ChangeNameButton.setVisible(false);
            ChangeNameButton.setEnabled(false);
            
        }
        
    }
    
    public void translate (int x, int y) {
        setLocation(getX()+x, getY()+y);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ButtonContainer;
    private javax.swing.JButton ChangeNameButton;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JButton ExitButton;
    private javax.swing.JScrollPane ScrollPane;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
