/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.western;

import java.awt.*;
import javax.swing.ComboBoxModel;
import javax.swing.Icon;
import org.kordamp.ikonli.remixicon.RemixiconAL;
import org.kordamp.ikonli.remixicon.RemixiconMZ;
import org.kordamp.ikonli.swing.FontIcon;

/**
 *
 * @author Liam
 */
public class POIPopup extends javax.swing.JPanel {

    private POI POI;
    private boolean editing;
    
    private static Icon favouritedIcon, notFavouritedIcon;
    
    /**
     * Creates new form POIPopup
     */
    public POIPopup(POI POI) {
        
        this.POI = POI;
        editing = false;
        initComponents();
        
        fillTextBoxes();
        initButtons();
        
    }

    private void fillTextBoxes() {
        
        POINameField.setText(POI.getName());
        RoomNameField.setText("Room: " + POI.getRoom().getRoomNumber());
        BuildingNameField.setText(POI.getBuilding().getName());
        DescriptionTextField.setText(POI.getDescription());
        
        for (Layer layer:Map.getLayers()) {
            LayerSelector.addItem(layer.getName());      
        }
        LayerSelector.setSelectedItem(POI.getLayer().getName());
        
    }
    
    private void initButtons() {
        
        //set exit button icons
        ExitButton.setIcon(FontIcon.of(RemixiconAL.CLOSE_FILL, 24));
        ExitButton.setPressedIcon(FontIcon.of(RemixiconAL.CLOSE_FILL, 24, Color.RED));
        //
        
        //set favourite button icons
        favouritedIcon = FontIcon.of(RemixiconMZ.STAR_FILL, 24);
        notFavouritedIcon = FontIcon.of(RemixiconMZ.STAR_LINE, 24);
        
        System.out.println(MainWindow.curUser);
        if (MainWindow.curUser != null) {
            if (POI.isFavourite(MainWindow.curUser)) 
                favouriteButton.setIcon(favouritedIcon);
            else favouriteButton.setIcon(notFavouritedIcon);
        }
        else favouriteButton.setIcon(notFavouritedIcon);
        //favouriteButton.setPressedIcon(FontIcon.of(RemixiconMZ.STAR_FILL, 24));
        //
        
        //hide save and delete buttons
        SaveButton.setVisible(false);
        SaveButton.setEnabled(false);
        DeleteButton.setVisible(false);
        DeleteButton.setEnabled(false);        
        //
        
        //disable layer selection
        LayerSelector.setEnabled(false);
        
    }
    
    public void close() {
        
        Container parent = this.getParent();
        parent.remove(this);
        parent.revalidate();
        parent.repaint();
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        POINameField = new javax.swing.JTextField();
        BuildingNameField = new javax.swing.JTextField();
        RoomNameField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        DescriptionTextField = new javax.swing.JTextArea();
        DescriptionLabel = new javax.swing.JLabel();
        EditButton = new javax.swing.JButton();
        SaveButton = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();
        favouriteButton = new javax.swing.JToggleButton();
        DeleteButton = new javax.swing.JButton();
        LayerSelector = new javax.swing.JComboBox<>();

        POINameField.setEditable(false);
        POINameField.setText("POI_NAME");

        BuildingNameField.setEditable(false);
        BuildingNameField.setText("BUILDING_NAME");

        RoomNameField.setEditable(false);
        RoomNameField.setText("ROOM_NAME");

        DescriptionTextField.setEditable(false);
        DescriptionTextField.setColumns(20);
        DescriptionTextField.setRows(5);
        jScrollPane1.setViewportView(DescriptionTextField);

        DescriptionLabel.setText("Description:");

        EditButton.setText("Edit");
        EditButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditButtonMouseClicked(evt);
            }
        });

        SaveButton.setBackground(new java.awt.Color(51, 51, 255));
        SaveButton.setForeground(new java.awt.Color(255, 255, 255));
        SaveButton.setText("Save");
        SaveButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SaveButtonMouseClicked(evt);
            }
        });

        ExitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitButtonMouseClicked(evt);
            }
        });

        favouriteButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                favouriteButtonMouseClicked(evt);
            }
        });
        favouriteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                favouriteButtonActionPerformed(evt);
            }
        });

        DeleteButton.setBackground(new java.awt.Color(255, 51, 51));
        DeleteButton.setForeground(new java.awt.Color(255, 255, 255));
        DeleteButton.setText("delete");
        DeleteButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteButtonMouseClicked(evt);
            }
        });
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });

        LayerSelector.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                LayerSelectorItemStateChanged(evt);
            }
        });
        LayerSelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LayerSelectorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(DescriptionLabel)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(BuildingNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(RoomNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(LayerSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(POINameField))
                        .addGap(70, 70, 70)
                        .addComponent(ExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(DeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(SaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EditButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(favouriteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(POINameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BuildingNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RoomNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LayerSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DescriptionLabel)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(favouriteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(SaveButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(EditButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(DeleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ExitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitButtonMouseClicked
        close();
    }//GEN-LAST:event_ExitButtonMouseClicked

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void favouriteButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_favouriteButtonMouseClicked
        if (MainWindow.curUser != null) {
            if (POI.isFavourite(MainWindow.curUser)) {
                MainWindow.curUser.removeFavouritePOI(POI);
                favouriteButton.setIcon(notFavouritedIcon);
            }
            else {
                MainWindow.curUser.addFavouritePOI(POI);
                favouriteButton.setIcon(favouritedIcon);
            }
        }
    }//GEN-LAST:event_favouriteButtonMouseClicked

    private void favouriteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_favouriteButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_favouriteButtonActionPerformed

    private void EditButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditButtonMouseClicked
        editing = !editing;
        
        //show/hide save and delete buttons
        SaveButton.setVisible(editing);
        SaveButton.setEnabled(editing);
        DeleteButton.setVisible(editing);
        DeleteButton.setEnabled(editing);        
        //

        POINameField.setEditable(editing);
        DescriptionTextField.setEditable(editing);
        LayerSelector.setEnabled(editing);
        
    }//GEN-LAST:event_EditButtonMouseClicked

    private void SaveButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SaveButtonMouseClicked
        
        POI.setName(POINameField.getText());
        POI.setDescription(DescriptionTextField.getText());
        //switch layers if changed
        String selected = (String)LayerSelector.getSelectedItem();
        if (!selected.equals(POI.getLayer().getName())) {
            POI.switchLayer(Map.getLayer(selected));
        }
        //
        EditButtonMouseClicked(evt);
        
    }//GEN-LAST:event_SaveButtonMouseClicked

    private void DeleteButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteButtonMouseClicked
        
        POI.delete();
        close();
        
    }//GEN-LAST:event_DeleteButtonMouseClicked

    private void LayerSelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LayerSelectorActionPerformed
        
    }//GEN-LAST:event_LayerSelectorActionPerformed

    private void LayerSelectorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_LayerSelectorItemStateChanged
        
    }//GEN-LAST:event_LayerSelectorItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BuildingNameField;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JLabel DescriptionLabel;
    private javax.swing.JTextArea DescriptionTextField;
    private javax.swing.JButton EditButton;
    private javax.swing.JButton ExitButton;
    private javax.swing.JComboBox<String> LayerSelector;
    private javax.swing.JTextField POINameField;
    private javax.swing.JTextField RoomNameField;
    private javax.swing.JButton SaveButton;
    private javax.swing.JToggleButton favouriteButton;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
